# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true
org.gradle.daemon = false
fabric.loom.ignoreDependencyLoomVersionValidation = true
fabric.loom.allowMismatchedPlatformVersions = true
fabric.loom.multiProjectOptimisation = false

# Project
mod_id = feudalist
mod_name = Feudalist
mod_version = 1.21.1-1.0.0
mod_author = MehVahdJukaar
mod_description = AMogus
mod_license = Supplementaries Team License v.1.5
mod_authors = Plantkillable, MehVahdJukaar
mod_homepage = https://www.curseforge.com/minecraft/mc-mods/feudalist
mod_credits = Plantkillable, MehVahdJukaar
mod_github = https://github.com/MehVahdJukaar/feudalist

release_type = release
maven_group = net.mehvahdjukaar

# Publishing
repository = MehVahdJukaar/feudalist
modrinth_project_id = feudalist

# MC / loader versions
mc_version = 1.21.1

neoforge_version = 21.1.248

fabric_loader_version = 0.19.3
fabric_api_version = 0.116.15+1.21.1

parchment_mappings_version = 2024.11.17

# Mod-specific dep versions
moonlight_version = 1.21.1-3.5.0
moonlight_min_version = 1.21.1-3.5.0
codecui_version = 1.21.1-1.3.6
